### PR TITLE
Fix contactform

### LINKED ISSUE #17: Email contactform does not function, returns 405 instead
When you fill out the contact form at the bottom of the site, and try to send; you are redirected to a 405. 

From what I gathered from Martin (Weidner), this was supposed to be some service we made use of to send the email without it actually opening an email on your client.

### PR DESCRIPTION
**Pull request by Bjeaurn**
Fixes #17

### CODE REVIEW

File: app/js/ContactForm.js [hunk 1]
```diff
@@ -1,25 +1,27 @@
...
-        messageData[field.name] = field.value;
+      .on('submit', function(e) {
+        e.preventDefault();
+      })
+      .on('formvalid.zf.abide', function(e,$form) {
+        e.preventDefault();
+        let messageData = that.createMessageData($form)
+        that.submitForm(messageData);
+      })
+      .on('forminvalid.zf.abide', function(e, $form) {
```
Comment (mozartdiniz) [inline app/js/ContactForm.js]: If you use ArrowFunctions you will not have this context issue:

```javascript
    .on('formvalid.zf.abide', (e,$form) => {
        e.preventDefault();
        let messageData = this.createMessageData($form);
        that.submitForm(messageData);
     })
```

File: app/js/ContactForm.js [hunk 2]
```diff
@@ -1,25 +1,27 @@
...
-      let messageData = {};
-      serializedForm.map(field => {
-        messageData[field.name] = field.value;
+      .on('submit', function(e) {
+        e.preventDefault();
+      })
+      .on('formvalid.zf.abide', function(e,$form) {
+        e.preventDefault();
+        let messageData = that.createMessageData($form)
+        that.submitForm(messageData);
```
Comment (mozartdiniz) [inline app/js/ContactForm.js]: messageData can be a constant, or we can event remove it.

```javascript
    that.submitForm(that.createMessageData($form));
```

File: app/js/ContactForm.js [hunk 3]
```diff
@@ -40,4 +43,13 @@ export class ContactForm {
       $('.email-fail').toggle('slow');
     });
   }
+
+  createMessageData($form) {
+    let serializedForm = $form.serializeArray();
```
Comment (mozartdiniz) [inline app/js/ContactForm.js]: const

**Review by mozartdiniz — CHANGES_REQUESTED** [review]

File: app/js/ContactForm.js (hunk 2 above)
Comment (Bjeaurn) [reply app/js/ContactForm.js]: Turning it into a constant sounds good, I'll do that.

File: app/js/ContactForm.js [hunk 4]
```diff
@@ -41,3 +40,12 @@ export class ContactForm {
...
 }
+
+function createMessageData($form) {
+  let serializedForm = $form.serializeArray();
+  let messageData = {};
+  serializedForm.map(field => {
+    messageData[field.name] = field.value;
+  });
+  return messageData;
+}
```
Comment (mozartdiniz) [inline app/js/ContactForm.js]: This is just a suggestion because people prefer doing this in different ways:

```javascript
function createMessageData($form) {
  return $form.serializeArray().map(field => {
    messageData[field.name] = field.value;
  });
 }
```

**Review by mozartdiniz — APPROVED** [review]

File: app/js/ContactForm.js (hunk 4 above)
Comment (Bjeaurn) [reply app/js/ContactForm.js]: I don't mind doing it that way, I just took the original piece of code. Could've boy scouted a bit more. It doesn't necessarily make it less readable, so I'll do it like that as a precedent ;-).
